TOP = ../..
include $(TOP)/mk/boilerplate.mk

HS_SRCS = ListAux.hs SumEulerPrimes.hs SumEuler.hs
PROG_ARGS = 38 8000 100
SRC_HC_OPTS += -package parallel

# FAST_OPTS = 
# NORM_OPTS = 
# SLOW_OPTS = 

include $(TOP)/mk/target.mk
